use_frameworks!
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ours-curiosity/CTSpecs'

target 'CTWebSocket_Example' do
  pod 'CTWebSocket', :path => '../'

end
